### PR TITLE
Mention usethis::edit_r_environ() 

### PR DESCRIPTION
**Pull request by romainfrancois**
Unfortunately I could not render the `README.md` 😬  as part of this pr because `get_events(urlname)` had nothing to return.

### CODE REVIEW

**Comment by gdequeiroz** [comment]
Thank you @romainfrancois! I think the reason you didn't get anything from the `get_events(urlname)` was because the default is `get_events(urlname, event_status = "upcoming", api_key = NULL)` and since there are no "upcoming" events in SF, it has nothing to return.

**Review by gdequeiroz — APPROVED** [review]
LGTM!

**Comment by romainfrancois** [comment]
I changed it to past events then (and could not resist `dplyr::arrange` them in `desc` created time 😇

**Comment by gdequeiroz** [comment]
Beautiful! Thank you @romainfrancois.

**Pull request merged**
