### PR TITLE
Giving the 📦 a little love!

### PR DESCRIPTION
**Pull request by LucyMcGowan**
**Major Changes:**
* Rather than outputting a gnarly list, all functions now output a tibble with a few key pieces pulled out, with the gnarly list saved as a list-col
* Sets the expectation that the API key is saved in your environment as `MEETUP_KEY` - this is checked first.
* Renamed functions to stay consistent (rather than `get_meetup_attendence()` and `get_meetup_comments()`, now it is just `get_attendence()` and `get_comments()` to align with the other function names).
* Switched roxygen documentation to markdown.

**Minor Changes:**
* Doc updated
* removed dplyr dependency (we weren't using it)
* added tibble and purrr dependency

### CODE REVIEW

**Comment by ledell** [comment]
@LucyMcGowan Here are the edits that we discussed making to this PR.  We can use this to track the progress of outstanding items.  If you like, feel free to break some or all these tasks out into Issues and assign them to whoever is going to work on them.

- [x] Increase the version number to 0.1.0.
- [x] Document new dependencies (**purr**, **tibble**) in NEWS file (also, add a NEWS file).
- [x] Change `date_helper()` and `get_api_key()` to be hidden functions, `.date_helper()` and `.get_api_key()`.
- [x] Keep the name of the raw list output column the same across all functions, so rather than `attendees_resource`, `comments_resource`, it could just be called `resource` or something more descriptive like `raw_result` consistency across all functions.
- [x] For column names in the result set -- let's keep the names that the meetup API uses.  For example, in the `get_events()` function, there's currently an `n_rsvp` column, but the meetup API calls this `yes_rsvp_count`.  
- [x] Let’s change the function names from `get_meetup_something()` to `get_event_something()` to re-align more closely with the meetup API terminology and use the `.Deprecated()` function to deprecate the `get_meetup_something()` versions.  
- [x] Update argument defaults (can do here or in a separate PR): https://github.com/rladies/meetupr/issues/12

**Comment by ledell** [comment]
@LucyMcGowan Some follow-up questions: 
1. Should we move **purr** and **tibble** from "Imports" to "Depends", or is there a fall-back mechanism if they're not installed?
2. Should we consider adding a `return_raw = FALSE` (or similarly named) arg to all the functions so that the user can get the data in raw list format if that's what they prefer and/or for backwards compatibility?

**Comment by LucyMcGowan** [comment]
@ledell: Sorry this took so long! Finally have some time to get back to this. I've done a few things you mention above, but I have a few follow up questions:

* What is the benefit of having the functions "hidden" (this is a genuine question, I just haven't included functions that start with `.` in my packages before) -- if I don't export them, they won't be revealed to the user unless the `:::` is used, correct?
* I am leaning towards leaving `*_resource` rather than changing them all to have the same column name because if someone wanted to merge together multiple tibbles, we'd want each resource from a different endpoint to have it's own descriptive column (rather than get jumbled if they all have the same name)
* I am not sure how to use the `.Deprecated()` function :see_no_evil: do you have a small example / resource you can  point me to?
* My understanding is purrr and tibble can remain as "Imports" because I use `::` every time they're used.
* I don't feel great about `return_raw = FALSE` because I don't love the idea of a function returning a different class of output based on input (but perhaps we can have small functions that always return the raw data and have the new functions that return the nice tibbles wrap those?

**Comment by ledell** [comment]
Hey @LucyMcGowan!  Here are some responses to your follow-up questions:

> What is the benefit of having the functions "hidden" (this is a genuine question, I just haven't included functions that start with . in my packages before) -- if I don't export them, they won't be revealed to the user unless the ::: is used, correct?

One reason for doing this is to obscure them, because they are not meant to accessed by the end-user.  Before Roxygen, I think this was the only way to allow functions to not appear in the documentation, so there may be some historical aspect of this.  The other reason is that this allow the developer to easily modify these functions w/o API breakage.  This sends a clear message that these functions are not user-facing functions and should not really be used.  Another thing that people do is write helper functions inside of another function, but that only works if you only use it in a single function.  The trend nowadays is to have them outside the function (for version control reasons, it's more clear to see edits as well when they are outside of other functions).

Though I am looking at  `get_api_key()` right now and it seems like I might be wrong about how you intended this function to be used.  I had assumed that if the `api_key` was not passed by the user (we can default  `api_key = NULL` in all the functions), then internally, if `api_key` was left as `NULL`, then we'd use the `get_api_key()` function inside the `get_members()` function, for example, to retrieve the API key and then the user would never have to worry about setting the `api_key` variable at all.  This is why I thought it made sense as an internal function.  But now that I am looking, I don't see `get_api_key()` currently used in any functions, so maybe your intention was for the user to use it at the top of their script to get it once, save it in a variable, and then pass it along to all the functions...

> I am leaning towards leaving *_resource rather than changing them all to have the same column name because if someone wanted to merge together multiple tibbles, we'd want each resource from a different endpoint to have it's own descriptive column (rather than get jumbled if they all have the same name)

I'm not sure I follow since all the functions return a different type of data (events, members, etc), so it doesn't make sense to merge rows that represent different things.  We already use common/generic names already like `id`, `name`, etc. so using another generic name brings internal consistency and predictability across all the functions.

I am also wondering if there is a more descriptive column name that we can use, like "result" or "raw_result".  Where does the term, "resource", come from, is it used in the meetup API?

> I am not sure how to use the .Deprecated() function 🙈 do you have a small example / resource you can point me to?

Sure, here's an [example](https://github.com/tidyverse/dplyr/blob/3564a0605feae76286ddb4e1d1526d91f16b3319/R/rbind.R#L55) from **dplyr**.

> My understanding is purrr and tibble can remain as "Imports" because I use :: every time they're used.

Ok that sounds good and you're right that it's okay to use Imports and not Depends even if our package "depends" on those functions. From Hadley's [R Packages book](http://r-pkgs.had.co.nz/namespace.html): 

```
Depends is just a convenience for the user: if your package is attached, it also attaches all packages listed in Depends. If your package is loaded, packages in Depends are loaded, but not attached, so you need to qualify function names with :: or specifically import them.
```

> I don't feel great about return_raw = FALSE because I don't love the idea of a function returning a different class of output based on input (but perhaps we can have small functions that always return the raw data and have the new functions that return the nice tibbles wrap those?

~~Lets talk to some people (maybe in rOpenSci or the new RStudio community site) and see if there is a consensus on this... I don't know this is gently discouRaged, or if this type of thing is sacRilegious.  My current impression is that it's not recommended unless there is some large benefit to doing so, achievable in no other way.  There are two benefits that I can think of:~~
1. ~~This makes our package almost fully backwards compatible (all they'd have to do is add `return_raw = TRUE` to their functions).  Since we're not on CRAN yet, this is less important.~~
2. ~~This allows the user to parse the raw data so they can grab stuff that we are currently not providing in the tibble that's returned.~~

~~The latter is more important than the first.  However, like you suggested, maybe we could separate the functions.  One option is to duplicate the functions, e.g. `get_members_raw()`  What do you think of that option?~~

**Edit:** Wait, is it as easy to get the original/raw result list back as doing something like this?
```
res <- as.list(res_tibble$result)  #where result is the current *_resource col
```
If so, then that's probably sufficient.

**Comment by LucyMcGowan** [comment]
Thank you @ledell!

* Ah! I see. I *think* by not using the roxygen `@export` it achieves the same thing? but I will add a . for continuity (I use `get_api_key()` in `.quick_fetch()`)

* re:  leaving *_resource: It think I was thinking if you pulled data for a series of particular events, but also wanted to merge with metadata about each meetup (like members) maybe we'd need different columns? But you're comment about us reusing other columns like `id` etc. settles this, I think you're right we should change it to just `resource`.

* Thank you for the dplyr example!

*  I like the idea of a separate function like `get_members_raw()`, alternatively, the `resource` column of each tibble **is** what would be output from a function like `get_members_raw()` (it is the direct raw output from the API), so maybe we could just direct folks there?

I'll work on these updates and push soon!

**Comment by LucyMcGowan** [comment]
Ah I just realized the merge from @cvitolo overwrote my use of `get_api_key()` in `.quick_fetch()` (which is why you didn't see it) -- I'll leave it out for now, but may re-incorporate it later.

**Comment by LucyMcGowan** [comment]
@ledell I've made most of the updates -- I still don't understand the `.Deprecated()` example from dplyr -- is the function that is getting deprecated put in? What would I put for the remainder of the function that contains the `.Deprecated()` call?

**Comment by ledell** [comment]
Hey @LucyMcGowan, thanks for the updates!  I can work on finishing the rest -- I'll make the updates on a branch, and then create a PR for your branch so you can check out my changes first.  Sorry for merging @cvitolo's branch -- I failed to notice that it was going to overwrite anything (my bad).  I will add this back in.

**Comment by LucyMcGowan** [comment]
Sounds good -- thank you! (No worries re: merging!)

**Comment by ledell** [comment]
@LucyMcGowan Did you want to review and merge @cvitolo's new [PR](https://github.com/rladies/meetupr/pull/16) before I get started?

**Review by ledell — APPROVED** [review]
Looks great, we are good to go!

**Pull request merged**
