### PR TITLE
Return null

### PR DESCRIPTION
**Pull request by drmowinckels**
when the groups has no events, the handler fails because of the renaming of data columns that dont exist. Function nor returns `NULL` if there is no data.

I have also replaced the use of magrittr pipe with base pipe, and done some minor simplifications of the dplyr calls.

### CODE REVIEW

**Review by ledell — APPROVED** [review]
Awesome, thanks @Athanasiamo!

**Comment by ledell** [comment]
@Athanasiamo Oh, regarding the change of all the pipes from `%>%` to `|>` which limits to users of 4.0(?) and above.  We talked about possibly holding off on this -- do you want to revert that for now?  Also if we did make that change, would we need to declare a version of R that's supported in DESCRIPTION or how is that documented?

**Comment by drmowinckels** [comment]
The only place the pipe is left now, is in the main vignette. No internals use any pipe anymore ([dont pipe, create custom rename func](https://github.com/rladies/meetupr/pull/139/commits/cdfc26408479bbb5a1e8c9ff49ae593b0835303b))

But I can change the pipe in the vignette too, if thats gonna break things (I guess it might)

**Comment by drmowinckels** [comment]
@ledell I switched back to magrittr pipe (I acutally made new commits rather than revert, because of the other stuff I did. But we can squash merge this entire branch when ready.

**Comment by ledell** [comment]
That's perfect, thank you!

**Pull request merged**
