### PR TITLE
Add purrr defaults to more get_events() API calls

### PR DESCRIPTION
**Pull request by GregSutcliffe**
So I was hitting some of the issues listed in #29 (which seems to have stalled), but I thought it might be pragmatic to handle the errors being caused by the MeetUp API. I've hit errors in all 4 of these fields while processing a set of about 120 MeetUp groups, but this should be a minimal reproduction:

```
library(meetupr)
Sys.setenv(MEETUP_KEY = "mykey")
get_events('AnsibleCU','past') # private group
rlang::last_trace() # error in `created`, but fixing that then shows an error in `status`
get_events('Ansible-Leeds','cancelled') # time errors
rlang::last_trace() # error in `time`, but fixing that then shows an error in `local_date`
```

Fixing these 4 has allowed me to process the whole list of meetups without error. This is my first contribution to an R package, so happy to change anything, feedback, etc. Thanks!

### CODE REVIEW

**Review by LucyMcGowan — COMMENTED** [review]
This looks great. @GregSutcliffe, a few quick things: 

* it looks like we use the deprecated `.null` parameter for this in a few places, would you be interested in updating those to the proper `.default` for us for consistency?
* Can you add yourself as `ctb` to the author list in the DESCRIPTION file?

👏 yay for a first R contribution!

**Comment by GregSutcliffe** [comment]
@lucymcgowan yeah, I think I can do that, I'll take a look tomorrow. Thanks for the review! :tada:

**Comment by GregSutcliffe** [comment]
@LucyMcGowan I've rebased off master, added the `ctb` role and replaced the `.null`s in the `get_events` call. Did you want me to do the other files in `R/` too?

Retested for my use case, still works (as you'd expect, since it's just replacing a deprecated call with the new one).

**Comment by LucyMcGowan** [comment]
Awesome thank you! If you don’t mind it’d be great if you could fix all the `.null` calls

**Comment by GregSutcliffe** [comment]
@LucyMcGowan sure, search/replace isn't too hard to do :)

So I think that's all of them, I've given it a quick test for my usecase and seems OK - but that's touched a  lot of methods. Could you give it a try and make sure it's not broken?

**Comment by GregSutcliffe** [comment]
@LucyMcGowan any update? I know you're busy, but it's been a month :)

**Comment by LucyMcGowan** [comment]
Sorry I lost track of this! Looks good to me :+1: @ledell do you want to give a final look, or should I merge?

**Comment by GregSutcliffe** [comment]
Thanks @LucyMcGowan, I'd kinda forgotten myself until this OAuth thing came up and had to dive back into the package.

**Comment by GregSutcliffe** [comment]
@ledell any chance of a merge while I'm working on the OAuth stuff? It's getting tedious to rebase these two commits in and out of HEAD while I test the OAuth code on my Meetup groups :)

**Comment by ledell** [comment]
@GregSutcliffe Sorry, sure thing!

**Pull request merged**
