### PR TITLE
Vignettes

### PR DESCRIPTION
**Pull request by cvitolo**
Added more analytics and the calculation of growth to the vignette

### CODE REVIEW

**Comment by gdequeiroz** [comment]
@cvitolo - this is soooo needed. Thank you! 🙌 I think this should go in the https://github.com/rladies/rladies-metrics repo instead (or as well). I think the analysis is more specific to our R-Ladies Global case and the vignette should be more generic as possible. What do you think? (I don't have a strong preference. This is just a thought)

**Comment by cvitolo** [comment]
Thanks @gdequeiroz!
We could copy this to rladies_metrics as well. I'll change the content here to something more generic in the future

**Review by ledell — APPROVED** [review]
Somehow I just saw this... is this okay to merge?  Thank you @cvitolo!

**Comment by cvitolo** [comment]
Hi @ledell, yes you can merge this. Thanks a lot!

**Pull request merged**
