### PR TITLE
Create empty list instead of throwing error when no results returned …

### PR DESCRIPTION
**Pull request by missaugustina**
…from api

Fixes Issue #62

### CODE REVIEW

**Comment by missaugustina** [comment]
I need to write checks for other methods to make sure this doesn't break those.

**Comment by missaugustina** [comment]
Haven't done a full end-to-end test on my own, just unit tests.

**Comment by ledell** [comment]
Hi @missaugustina I'm sorry that this never got merged... Can you try this out with the latest code and let me know if your tests still pass?  I'd love to merge this if possible.

**Comment by maelle** [comment]
@ledell maybe easier to close this?

**Comment by maelle** [comment]
Actually it already works on the default branch.

``` r
meetupr::get_events("rladies-nashville")
#> Warning: Zero records match your filter. Nothing to return.

#> Warning: Zero records match your filter. Nothing to return.
#> Downloading 0 record(s)...
#> # A tibble: 0 x 21
#> # … with 21 variables: id <chr>, name <chr>, created <dttm>, status <chr>,
#> #   time <dttm>, local_date <date>, local_time <chr>, waitlist_count <int>,
#> #   yes_rsvp_count <int>, venue_id <int>, venue_name <chr>, venue_lat <dbl>,
#> #   venue_lon <dbl>, venue_address_1 <chr>, venue_city <chr>,
#> #   venue_state <chr>, venue_zip <chr>, venue_country <chr>, description <chr>,
#> #   link <chr>, resource <list>
```

<sup>Created on 2021-01-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Pull request closed without merging**
