### PR TITLE
GraphQL: rewrite remaining functions

### PR DESCRIPTION
**Pull request by benubah**
Continues the work from here: https://github.com/rladies/meetupr/pull/123

- Make new functions:
- [x]  `get_event_attendees2()`
- [x] `get_event_comments2()`
- [x] `get_event_rsvps2()`
- [x] `get_members2()`
- [ ] `get_pro2()`
- [x] `meetup_query2()`. Similar to `graphql_query()`

### CODE REVIEW

**Comment by benubah** [comment]
The fastest way to start testing might be to take a look at: https://github.com/rladies/meetupr/blob/ben/R/graphql.R#L431-L451

**Comment by benubah** [comment]
We already started testing here: https://github.com/rladies/meetupr/issues/137

**Review by ledell — COMMENTED** [review]
Merging into master so we have something working agin, will try to do a full review afterwards.

**Comment by ledell** [comment]
@benubah Per your suggestion, I am just merging this so we can get something functional on the master branch.  The `get_pro()` work can be done on a follow-up branch, after we have a chance to review this work and give feedback.

**Comment by ledell** [comment]
@benubah Can you update the README to reference the new functions and current state of the package so that it's easier for people to know where to start on their reviews?

**Comment by benubah** [comment]
@ledell Thanks! Yes, will update!

**Pull request merged**
