### PR TITLE
Add pkgdown

### LINKED ISSUE #72: Make a pkgdown webpage hosted on GitHub
It would be nice to have a simple [pkgdown](https://pkgdown.r-lib.org/) website.  We could host it at: https://rladies.github.io/meetupr

### PR DESCRIPTION
**Pull request by malcolmbarrett**
This PR adds a simple pkgdown site (more or less keeping the pkgdown defaults) that deploys automatically to GitHub Pages via GitHub Actions whenever the main branch is updated. This renders well locally, and I've had good luck with the pkgdown GHA script, but it is difficult to confirm without push access. I don't foresee any issues, though. If GitHub Pages is active for the repo, it should deploy to https://rladies.github.io/meetupr upon merging. 

Closes #72

### CODE REVIEW

**Review by ledell — APPROVED** [review]
Thank you so much @malcolmbarrett!

**Comment by ledell** [comment]
Hi @malcolmbarrett I just merged it.  I enabled github pages right before the merge, which added the [`index.md`](https://github.com/rladies/meetupr/blob/gh-pages/index.md) file, and now I see that template file at [https://rladies.github.io/meetupr/](https://rladies.github.io/meetupr/) instead of the package homepage.  Do you know how to update that?  (Maybe it's because I enabled a theme?)

**Comment by malcolmbarrett** [comment]
Oh yikes! Yeah, I'm pretty sure that's due to a theme. Because the `gh-pages` branch isn't empty, the pkgdown GHA fails, too: https://github.com/rladies/meetupr/runs/1257454781?check_suite_focus=true.

Will removing the theme remove that file? 

I can't remember the circumstance, but I remember once bumping into a similar issue where there were some existing files on the branch. I think I needed to delete the `gh-pages` branch and then manually create and orphan a new one (I did something like this: https://thoughtbot.com/blog/its-for-the-orphans). But hopefully just removing the theme will work!

You may also need to re-run the action since it failed. You should be able to manually trigger it in the actions pane

**Comment by malcolmbarrett** [comment]
PS when we get it running, let me know if you want any tweaks, e.g. theme (which can be set in the pkgdown yaml file), and I can do another PR

**Comment by ledell** [comment]
Hey @malcolmbarrett, thanks the suggestions. I [removed](https://github.com/rladies/meetupr/commit/a54c52a418a5ce14e85844339a7a738365ac74c7) the theme files from gh-pages and now I am [re-running](https://github.com/rladies/meetupr/runs/1267012389) the action!  I'll report back...

**Comment by ledell** [comment]
@malcolmbarrett It's working! :-)

**Comment by malcolmbarrett** [comment]
Woohoo! Let me know if you want any adjustments 😄

**Comment by ledell** [comment]
It looks beautiful!  Thank you!

**Pull request merged**
